#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from std_msgs.msg import Float32, String, Bool
from tf2_ros import Buffer, TransformListener, LookupException, ConnectivityException, ExtrapolationException
from collections import deque
import math
import time

class ProximitySensorNode(Node):
    def __init__(self):
        super().__init__('proximity_sensor_node')

        # publisher for speed commands
        self.speed_pub = self.create_publisher(Float32, '/speed_command', 10)

        self.override_sub = self.create_subscription(String, '/override_ack',
            self.override_ack_callback,10)
        self.estop_sub = self.create_subscription(Bool, '/estop',
            self.estop_callback,10)

        # TF buffer and listener
        self.tf_buffer = Buffer()
        self.tf_listener = TransformListener(self.tf_buffer, self)

        # parameters
        self.declare_parameter('gripper_frame', 'soft_robotics_gripper_base_link')
        self.declare_parameter('block_frame', 'block1')
        self.declare_parameter('gripper_size_mm', 200.0) # approx size betw base_link and finger tip
        self.declare_parameter('buffer_size', 10)  # smoothing window
        self.declare_parameter('slow_speed', 0.2)
        self.declare_parameter('normal_speed', 1.0)
        self.declare_parameter('slow_distance_mm', 80.0)
        self.declare_parameter('stop_distance_mm', 40.0)

        self.gripper_frame = self.get_parameter('gripper_frame').get_parameter_value().string_value
        self.block_frame = self.get_parameter('block_frame').get_parameter_value().string_value
        self.gripper_size_mm = self.get_parameter('gripper_size_mm').get_parameter_value().double_value
        self.buffer_size = self.get_parameter('buffer_size').get_parameter_value().integer_value
        self.slow_speed = self.get_parameter('slow_speed').get_parameter_value().double_value
        self.normal_speed = self.get_parameter('normal_speed').get_parameter_value().double_value
        self.slow_distance_mm = self.get_parameter('slow_distance_mm').get_parameter_value().double_value
        self.stop_distance_mm = self.get_parameter('stop_distance_mm').get_parameter_value().double_value

        # circular buffer for distances
        self.dist_buffer = deque(maxlen=self.buffer_size)

        # timer to periodically check distance
        # TODO: change 0.1 to Hz parameter
        self.timer = self.create_timer(0.1, self.check_distance)

        # speed to know whether there's been a change
        # TOOD: add a subscriber to make sure no one else has been adjusting the speed
        self.current_speed = 1.0
        self.estopped = False
        self.acked = False

    def estop_callback(self, msg):
        self.estopped = msg.data
        if (self.estopped):
            self.current_speed = 0.0

    def override_ack_callback(self, msg):
        self.acked = (str(msg.data) == "ACCEPTED") # TODO: avoid hard-coding str

    def check_distance(self):
        if self.estopped:
            return
        try:
            now = rclpy.time.Time()
            trans = self.tf_buffer.lookup_transform(
                self.gripper_frame,
                self.block_frame,
                now
            )
        except (LookupException, ConnectivityException, ExtrapolationException):
            self.get_logger().warn(f"TF lookup failed between {self.gripper_frame} and {self.block_frame}", 
                throttle_duration_sec=1.0)
            return

        dx = trans.transform.translation.x
        dy = trans.transform.translation.y
        dz = trans.transform.translation.z
        dist = math.sqrt(dx*dx + dy*dy + dz*dz)

        self.dist_buffer.append(dist)

        # hysteresis: average distance over buffer
        avg_dist = sum(self.dist_buffer) / len(self.dist_buffer) * 1000.0 # in mm

        # remove gripper size (approx, with safety margin)
        avg_dist -= self.gripper_size_mm

        # determine speed command
        if avg_dist <= self.stop_distance_mm:
            speed = 0.0
        elif avg_dist <= self.slow_distance_mm:
            speed = self.slow_speed
        else:
            speed = self.normal_speed
        
        # keep sending speed commands until its ack'ed
        if speed != self.current_speed: #not self.acked or
            msg = Float32()
            msg.data = speed
            self.speed_pub.publish(msg)
            self.current_speed = speed
            self.acked = False
            self.get_logger().debug(f"Publishing! Speed={speed:.2f}")

        self.get_logger().info(f"Dist-size={avg_dist:.1f} mm -> Speed={speed:.2f}",
            throttle_duration_sec=2.0)


def main(args=None):
    rclpy.init(args=args)
    node = ProximitySensorNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()